### ISSUE TITLE
Update to Dioxus 0.5 to Enhance Newcomer Experience

### ISSUE THREAD

**Issue by RustGrow** [ishaaqziyan/Uchat-app#2]
Dear Jayson Lennon and Ishaaq,

First and foremost, I would like to express my appreciation for your application - it is truly magnificent and provides an excellent user experience.

I would like to suggest an update of your application to the latest version of Dioxus 0.5. The recent updates in Dioxus have introduced many new features that could significantly improve the understanding and interaction with the code, especially for newcomers. Some of the current implementations might be a bit confusing due to changes in Dioxus, and an update could help in easing the learning curve.

I would be grateful if you could consider the possibility of implementing this update. It will not only enhance the experience for new users but also help in maintaining the relevance of your application.
Dioxus discord https://discord.gg/XgGxMSkvUM

Best regards,
Vladimir.

**Comment by ishaaqziyan** [comment]
Thank you for the information, and noted with thanks.
Best,
Ishaaq

**Comment by ishaaqziyan** [comment]
Thank you for the information, and noted with thanks.
Best,
Ishaaq
